export type MuscleGroup =
  | 'Poitrine'
  | 'Dos'
  | 'Épaules'
  | 'Biceps'
  | 'Triceps'
  | 'Abdominaux'
  | 'Fessiers'
  | 'Quadriceps'
  | 'Ischio-jambiers'
  | 'Mollets'
  | 'Corps entier';

export type Difficulty = 'Débutant' | 'Intermédiaire' | 'Avancé';

export type Exercise = {
  id: string;
  name: string;
  description: string;
  difficulty: Difficulty;
  muscles: MuscleGroup[];
  instructions: string[];
  sets: string;
  reps: string;
  rest: string;
};

export const ALL_MUSCLE_GROUPS: MuscleGroup[] = [
  'Corps entier',
  'Poitrine',
  'Dos',
  'Épaules',
  'Biceps',
  'Triceps',
  'Abdominaux',
  'Fessiers',
  'Quadriceps',
  'Ischio-jambiers',
  'Mollets',
];

export const EXERCISES: Exercise[] = [
  // ── Poitrine ──────────────────────────────────────────────────────────────
  {
    id: 'push-up',
    name: 'Pompes classiques',
    description: 'Exercice fondamental au poids du corps pour la force du haut du corps.',
    difficulty: 'Débutant',
    muscles: ['Poitrine', 'Épaules', 'Triceps'],
    instructions: [
      'Position planche : mains écartées largeur d\'épaules, corps aligné.',
      'Descendre en pliant les coudes à 45°, poitrine proche du sol.',
      'Repousser jusqu\'à l\'extension complète sans verrouiller les coudes.',
      'Garder les abdominaux gainés tout au long du mouvement.',
    ],
    sets: '3–4',
    reps: '8–15',
    rest: '60s',
  },
  {
    id: 'push-up-wide',
    name: 'Pompes larges',
    description: 'Variante à prise large qui accentue le travail des pectoraux externes.',
    difficulty: 'Débutant',
    muscles: ['Poitrine', 'Épaules'],
    instructions: [
      'Placer les mains 15–20 cm plus larges que les épaules.',
      'Descendre lentement en gardant les coudes orientés vers l\'extérieur.',
      'Appuyer le sternum vers le sol pour maximiser l\'étirement.',
      'Remonter de façon explosive.',
    ],
    sets: '3',
    reps: '8–12',
    rest: '60s',
  },
  {
    id: 'push-up-diamond',
    name: 'Pompes diamant',
    description: 'Prise triangulaire sous le sternum — focus maximal sur les triceps et la ligne médiane.',
    difficulty: 'Intermédiaire',
    muscles: ['Poitrine', 'Triceps'],
    instructions: [
      'Former un triangle (diamant) avec les pouces et index sous le sternum.',
      'Garder les coudes serrés contre le corps lors de la descente.',
      'Descendre jusqu\'à effleurer le sol avec la poitrine.',
      'Pousser fort en expirant.',
    ],
    sets: '3',
    reps: '6–10',
    rest: '75s',
  },
  {
    id: 'dips-chair',
    name: 'Dips sur chaise',
    description: 'Mouvement de poussée verticale pour les triceps et la poitrine basse.',
    difficulty: 'Débutant',
    muscles: ['Triceps', 'Poitrine', 'Épaules'],
    instructions: [
      'S\'asseoir sur le bord d\'une chaise, mains à côté des hanches, doigts vers l\'avant.',
      'Avancer les fesses hors de la chaise, jambes tendues.',
      'Descendre en fléchissant les coudes jusqu\'à 90°.',
      'Remonter sans verrouiller les coudes en haut.',
    ],
    sets: '3',
    reps: '10–15',
    rest: '60s',
  },
  // ── Dos ───────────────────────────────────────────────────────────────────
  {
    id: 'superman',
    name: 'Superman',
    description: 'Extension dorsale au sol qui renforce l\'ensemble de la chaîne postérieure.',
    difficulty: 'Débutant',
    muscles: ['Dos'],
    instructions: [
      'Allongé face au sol, bras tendus au-dessus de la tête, jambes jointes.',
      'Contracter fessiers et dos pour soulever simultanément bras et jambes.',
      'Maintenir la position haute 2 secondes, corps en U inversé.',
      'Redescendre lentement sans toucher le sol.',
    ],
    sets: '3',
    reps: '12–15',
    rest: '45s',
  },
  {
    id: 'good-morning',
    name: 'Good Morning (poids du corps)',
    description: 'Inclinaison du buste pour renforcer les érecteurs du rachis et les ischio-jambiers.',
    difficulty: 'Débutant',
    muscles: ['Dos', 'Ischio-jambiers', 'Fessiers'],
    instructions: [
      'Debout, pieds largeur de hanches, mains derrière la nuque (pas tirées).',
      'Garder le dos plat et charnière à la hanche, non à la taille.',
      'Incliner le buste à environ 45–60° devant.',
      'Revenir à la verticale en contractant les fessiers et le dos.',
    ],
    sets: '3',
    reps: '12–15',
    rest: '60s',
  },
  {
    id: 'inverted-row',
    name: 'Rowing inversé (table)',
    description: 'Tirage horizontal au poids du corps avec une table — antagoniste des pompes.',
    difficulty: 'Intermédiaire',
    muscles: ['Dos', 'Biceps', 'Épaules'],
    instructions: [
      'S\'allonger sous une table solide, saisir le bord dessus en pronation.',
      'Corps gainé, talons au sol — corps droit comme une planche.',
      'Tirer la poitrine vers le bord de la table en rétractant les omoplates.',
      'Descendre lentement sur 3 secondes.',
    ],
    sets: '3',
    reps: '8–12',
    rest: '75s',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    description: 'Exercice de stabilisation lombaire et proprioceptif en quadrupédie.',
    difficulty: 'Débutant',
    muscles: ['Dos', 'Abdominaux', 'Fessiers'],
    instructions: [
      'À quatre pattes, dos plat, regard vers le sol.',
      'Étendre simultanément le bras droit et la jambe gauche, horizontalement.',
      'Maintenir 3 secondes en contrôlant les rotations du bassin.',
      'Alterner côtés de façon fluide.',
    ],
    sets: '3',
    reps: '10/côté',
    rest: '45s',
  },
  // ── Épaules ───────────────────────────────────────────────────────────────
  {
    id: 'pike-push-up',
    name: 'Pike Push-up',
    description: 'Pompe en V inversé — charge maximale sur les deltoïdes antérieurs.',
    difficulty: 'Intermédiaire',
    muscles: ['Épaules', 'Triceps'],
    instructions: [
      'Position pompe puis monter les hanches haut pour former un V avec le corps.',
      'Plier les coudes vers l\'extérieur, tête vers le sol.',
      'Descendre jusqu\'à ce que la tête approche le sol.',
      'Repousser en gardant le V.',
    ],
    sets: '3',
    reps: '8–10',
    rest: '75s',
  },
  {
    id: 'lateral-raise',
    name: 'Élévations latérales',
    description: 'Isolation du deltoïde médian pour élargir la silhouette des épaules.',
    difficulty: 'Débutant',
    muscles: ['Épaules'],
    instructions: [
      'Debout, bras le long du corps, léger fléchissement des coudes.',
      'Élever les bras latéralement jusqu\'à l\'horizontale (niveau des épaules).',
      'Maintenir 1s en haut, pouces légèrement en bas (vider la canette).',
      'Redescendre lentement sur 3 secondes.',
    ],
    sets: '3',
    reps: '12–15',
    rest: '45s',
  },
  {
    id: 'shoulder-press-floor',
    name: 'Développé épaules au sol',
    description: 'Presse verticale en appui sur les bras au sol — excellent sans matériel.',
    difficulty: 'Intermédiaire',
    muscles: ['Épaules', 'Triceps', 'Poitrine'],
    instructions: [
      'Assis les jambes croisées, mains à plat à côté des hanches.',
      'Pousser pour soulever les fesses du sol.',
      'Maintenir la position bras tendus 5–10 secondes.',
      'Travailler progressivement vers l\'extension complète.',
    ],
    sets: '3',
    reps: '5–8',
    rest: '90s',
  },
  // ── Biceps ────────────────────────────────────────────────────────────────
  {
    id: 'chin-up-negative',
    name: 'Traction en négatif',
    description: 'Descente contrôlée depuis la barre — construit rapidement la force des biceps.',
    difficulty: 'Intermédiaire',
    muscles: ['Biceps', 'Dos'],
    instructions: [
      'Monter en position haute (menton au-dessus de la barre) en sautant ou avec un escabeau.',
      'Descendre le plus lentement possible (viser 5–10 secondes).',
      'Résister jusqu\'à extension complète des bras.',
      'Ne pas lâcher brusquement pour protéger les tendons.',
    ],
    sets: '3',
    reps: '3–5',
    rest: '90s',
  },
  {
    id: 'curl-towel',
    name: 'Curl avec serviette',
    description: 'Flexion du coude en utilisant une serviette comme résistance isométrique ou dynamique.',
    difficulty: 'Débutant',
    muscles: ['Biceps'],
    instructions: [
      'Assis, passer une serviette sous la cuisse, saisir les deux bouts.',
      'Tirer la serviette vers le haut comme un curl tout en résistant avec la jambe.',
      'Monter sur 2s, maintenir 1s en haut, descendre sur 3s.',
      'Alterner jambes à chaque série.',
    ],
    sets: '3',
    reps: '10–12/côté',
    rest: '45s',
  },
  // ── Triceps ───────────────────────────────────────────────────────────────
  {
    id: 'tricep-extension-floor',
    name: 'Extension triceps au sol',
    description: 'Isolation des triceps en position couchée, sans équipement.',
    difficulty: 'Débutant',
    muscles: ['Triceps'],
    instructions: [
      'Allongé sur le dos, bras tendus à la verticale, paumes face à face.',
      'Plier uniquement les coudes, mains vers les oreilles.',
      'Maintenir les coudes fixes et pointant au plafond.',
      'Étendre les bras lentement.',
    ],
    sets: '3',
    reps: '12–15',
    rest: '45s',
  },
  {
    id: 'bench-dip',
    name: 'Dips pieds surélevés',
    description: 'Variante avancée des dips sur chaise avec les pieds posés sur une surface plus haute.',
    difficulty: 'Avancé',
    muscles: ['Triceps', 'Poitrine'],
    instructions: [
      'Mains derrière sur une chaise, pieds sur une autre chaise devant.',
      'Corps gainé, hanches dans l\'axe.',
      'Descendre les fesses vers le sol en pliant les coudes.',
      'S\'assurer que les épaules ne passent pas en dessous des coudes.',
    ],
    sets: '3',
    reps: '8–12',
    rest: '75s',
  },
  // ── Abdominaux ────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Planche frontale',
    description: 'Gainage isométrique fondamental pour la stabilisation du tronc.',
    difficulty: 'Débutant',
    muscles: ['Abdominaux', 'Dos'],
    instructions: [
      'En appui sur les avant-bras et les orteils, corps en ligne droite.',
      'Rentrer légèrement le nombril sans apnée.',
      'Contracter simultanément fessiers et abdos.',
      'Ne pas laisser le bassin tomber ou monter.',
    ],
    sets: '3',
    reps: '30–60s',
    rest: '45s',
  },
  {
    id: 'side-plank',
    name: 'Gainage latéral',
    description: 'Planche sur le côté ciblant l\'oblique et les muscles stabilisateurs du bassin.',
    difficulty: 'Débutant',
    muscles: ['Abdominaux'],
    instructions: [
      'En appui sur un avant-bras et le côté du pied (ou genou pour débutant).',
      'Corps en ligne droite de la tête aux pieds, bassin levé.',
      'L\'épaule d\'appui doit être directement sous le coude.',
      'Maintenir la position en respirant normalement.',
    ],
    sets: '3',
    reps: '20–40s/côté',
    rest: '30s',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    description: 'Exercice cardio-gainage qui sollicite les abdos fléchisseurs de hanche.',
    difficulty: 'Intermédiaire',
    muscles: ['Abdominaux', 'Corps entier'],
    instructions: [
      'Position de pompe haute, poignets sous les épaules.',
      'Ramener alternativement les genoux vers la poitrine en courant sur place.',
      'Garder le dos plat — ne pas laisser les hanches monter.',
      'Rythme rapide pour la cardio, lent pour le renforcement.',
    ],
    sets: '3',
    reps: '20–30/jambe',
    rest: '45s',
  },
  {
    id: 'bicycle-crunch',
    name: 'Crunch Bicyclette',
    description: 'Rotation du tronc ciblant les obliques et les transverses.',
    difficulty: 'Intermédiaire',
    muscles: ['Abdominaux'],
    instructions: [
      'Allongé, mains derrière la nuque (ne pas tirer), genoux fléchis.',
      'Soulever les épaules et ramener le genou gauche vers le coude droit.',
      'Alterner de façon fluide en pédalant.',
      'Le bas du dos reste en contact avec le sol.',
    ],
    sets: '3',
    reps: '15–20/côté',
    rest: '45s',
  },
  {
    id: 'hollow-hold',
    name: 'Hollow Body Hold',
    description: 'Position isométrique qui renforce la sangle abdominale profonde.',
    difficulty: 'Avancé',
    muscles: ['Abdominaux'],
    instructions: [
      'Allongé sur le dos, bras tendus au-dessus de la tête.',
      'Aplatir le dos au sol en contractant le transverse (pas de lordose).',
      'Soulever jambes, épaules et tête 15–20 cm du sol.',
      'Maintenir la position — prendre garde à ne pas cambrer.',
    ],
    sets: '3',
    reps: '20–40s',
    rest: '60s',
  },
  // ── Fessiers ──────────────────────────────────────────────────────────────
  {
    id: 'glute-bridge',
    name: 'Pont fessier',
    description: 'Mouvement de base pour activer et renforcer les fessiers.',
    difficulty: 'Débutant',
    muscles: ['Fessiers', 'Ischio-jambiers'],
    instructions: [
      'Allongé sur le dos, genoux fléchis à 90°, pieds à plat.',
      'Appuyer sur les talons pour soulever le bassin.',
      'Contracter fort les fessiers en haut, bassin dans l\'alignement.',
      'Maintenir 2s, descendre lentement sans toucher le sol.',
    ],
    sets: '3',
    reps: '15–20',
    rest: '45s',
  },
  {
    id: 'single-leg-bridge',
    name: 'Pont fessier unilatéral',
    description: 'Variante sur une jambe pour corriger les asymétries et augmenter la charge.',
    difficulty: 'Intermédiaire',
    muscles: ['Fessiers', 'Ischio-jambiers'],
    instructions: [
      'Même position que le pont classique mais une jambe tendue à 45°.',
      'Pousser sur le seul talon au sol pour lever le bassin.',
      'Garder le bassin horizontal (ne pas laisser le côté libre s\'affaisser).',
      'Alterner jambes après la série complète.',
    ],
    sets: '3',
    reps: '12–15/côté',
    rest: '60s',
  },
  {
    id: 'clamshell',
    name: 'Clamshell (ouverture de hanche)',
    description: 'Exercice ciblant le moyen fessier, fondamental pour la stabilité du bassin.',
    difficulty: 'Débutant',
    muscles: ['Fessiers'],
    instructions: [
      'Allongé sur le côté, genoux pliés à 90°, hanches à 45°, pieds ensemble.',
      'Ouvrir le genou supérieur comme une coquille de palourde, sans rouler le bassin.',
      'Maintenir 2s en haut, contrôler la descente.',
      'Ajouter un élastique au-dessus des genoux pour plus de résistance.',
    ],
    sets: '3',
    reps: '15–20/côté',
    rest: '30s',
  },
  {
    id: 'hip-thrust-floor',
    name: 'Hip Thrust au sol',
    description: 'Propulsion de hanches avec le dos sur un banc ou un canapé — force maximale des fessiers.',
    difficulty: 'Intermédiaire',
    muscles: ['Fessiers', 'Quadriceps'],
    instructions: [
      'Haut du dos appuyé sur le bord d\'un canapé, genoux fléchis.',
      'Descendre les hanches vers le sol puis propulser fort vers le haut.',
      'Contracter les fessiers au maximum en haut — corps à l\'horizontale.',
      'Ne pas hyperextendre le bas du dos.',
    ],
    sets: '4',
    reps: '12–15',
    rest: '60s',
  },
  // ── Quadriceps ────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Squat poids du corps',
    description: 'Mouvement fondamental pour la force des jambes et la mobilité des hanches.',
    difficulty: 'Débutant',
    muscles: ['Quadriceps', 'Fessiers'],
    instructions: [
      'Pieds largeur de hanches à légèrement plus larges, orteils légèrement vers l\'extérieur.',
      'Descendre en poussant les genoux vers l\'extérieur (dans l\'axe des pieds).',
      'Creuser jusqu\'à ce que les cuisses soient au moins parallèles au sol.',
      'Remonter en poussant dans le sol, expiration à la montée.',
    ],
    sets: '3–4',
    reps: '15–20',
    rest: '60s',
  },
  {
    id: 'jump-squat',
    name: 'Squat sauté',
    description: 'Squat explosif avec saut — développe la puissance des membres inférieurs.',
    difficulty: 'Intermédiaire',
    muscles: ['Quadriceps', 'Fessiers', 'Corps entier'],
    instructions: [
      'Descendre en squat (cuisses parallèles), dos droit.',
      'Propulser de façon explosive pour sauter le plus haut possible.',
      'Atterrir en souplesse sur l\'avant du pied, immédiatement en position squat.',
      'Minimiser le temps de contact au sol.',
    ],
    sets: '3',
    reps: '8–12',
    rest: '90s',
  },
  {
    id: 'lunge',
    name: 'Fentes avant',
    description: 'Exercice unilatéral pour l\'équilibre, la mobilité et la force des jambes.',
    difficulty: 'Débutant',
    muscles: ['Quadriceps', 'Fessiers', 'Ischio-jambiers'],
    instructions: [
      'Debout, faire un grand pas en avant, buste droit.',
      'Fléchir les deux genoux jusqu\'à ce que le genou arrière frôle le sol.',
      'Le genou avant ne dépasse pas la pointe du pied.',
      'Repousser avec le talon avant pour revenir.',
    ],
    sets: '3',
    reps: '10–12/jambe',
    rest: '60s',
  },
  {
    id: 'step-up',
    name: 'Step-up (marche sur banc)',
    description: 'Montée de marche pour renforcer les quadriceps et améliorer la proprioception.',
    difficulty: 'Débutant',
    muscles: ['Quadriceps', 'Fessiers'],
    instructions: [
      'Face à un banc ou une marche solide (30–50 cm), poser un pied dessus.',
      'Pousser sur le talon du pied posé pour monter, ne pas s\'aider avec la jambe arrière.',
      'Amener l\'autre jambe en haut, puis redescendre lentement.',
      'Alterner jambe en tête ou finir toutes les reps d\'un côté.',
    ],
    sets: '3',
    reps: '10–12/jambe',
    rest: '60s',
  },
  {
    id: 'wall-sit',
    name: 'Chaise au mur',
    description: 'Isométrie quadriceps — excellente pour la résistance à l\'effort soutenu.',
    difficulty: 'Débutant',
    muscles: ['Quadriceps', 'Fessiers'],
    instructions: [
      'Dos au mur, descendre jusqu\'à 90° (cuisses parallèles au sol).',
      'Pieds directement sous les genoux, pas devant.',
      'Appuyer le dos contre le mur sans cambrer.',
      'Respirer régulièrement et tenir le temps imparti.',
    ],
    sets: '3',
    reps: '30–60s',
    rest: '60s',
  },
  // ── Ischio-jambiers ────────────────────────────────────────────────────────
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    description: 'Exercice excentrique des ischio-jambiers — très efficace pour prévenir les blessures.',
    difficulty: 'Avancé',
    muscles: ['Ischio-jambiers'],
    instructions: [
      'À genoux, faire tenir les chevilles (pied de meuble ou partenaire).',
      'Descendre le buste vers le sol le plus lentement possible (4–6s).',
      'Utiliser les mains pour amortir en bas si nécessaire.',
      'Remonter en aidant avec les mains au bas puis contrôler avec les ischio.',
    ],
    sets: '3',
    reps: '4–6',
    rest: '120s',
  },
  {
    id: 'leg-curl-lying',
    name: 'Leg Curl allongé (élastique)',
    description: 'Flexion des genoux en position ventrale avec un élastique pour cibler les ischio-jambiers.',
    difficulty: 'Débutant',
    muscles: ['Ischio-jambiers'],
    instructions: [
      'Allongé face au sol, fixer un élastique à la cheville et à un point fixe devant.',
      'Fléchir le genou pour ramener le talon vers les fesses.',
      'Maintenir 1s, redescendre lentement contre la tension.',
      'Garder le bassin plaqué au sol.',
    ],
    sets: '3',
    reps: '12–15/jambe',
    rest: '60s',
  },
  {
    id: 'single-leg-deadlift',
    name: 'Deadlift unipodal',
    description: 'Équilibre et force ischio-jambiers en travail unilatéral — excellent pour les coureurs.',
    difficulty: 'Intermédiaire',
    muscles: ['Ischio-jambiers', 'Fessiers', 'Dos'],
    instructions: [
      'Debout sur une jambe, légère flexion du genou porteur.',
      'Charnière à la hanche : buste vers l\'avant, jambe libre s\'élève derrière.',
      'Descendre jusqu\'à ce que le buste soit à l\'horizontale (ou selon souplesse).',
      'Remonter en contractant le fessier de la jambe d\'appui.',
    ],
    sets: '3',
    reps: '8–10/jambe',
    rest: '75s',
  },
  // ── Mollets ───────────────────────────────────────────────────────────────
  {
    id: 'calf-raise',
    name: 'Élévations des mollets',
    description: 'Renforcement des gastrocnémiens et soléaires — essentiels pour les coureurs.',
    difficulty: 'Débutant',
    muscles: ['Mollets'],
    instructions: [
      'Debout, pieds largeur de hanches, bord de marche ou sol plat.',
      'Monter sur la pointe des pieds le plus haut possible.',
      'Maintenir 1s en haut, descendre lentement sous le niveau du sol si sur une marche.',
      'Pour progresser : ajouter une descente excentrique lente (4–5s).',
    ],
    sets: '3–4',
    reps: '20–25',
    rest: '45s',
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Élévations unilatérales des mollets',
    description: 'Version sur une jambe — charge doublée, très efficace pour la prévention des blessures.',
    difficulty: 'Intermédiaire',
    muscles: ['Mollets'],
    instructions: [
      'Sur une jambe, l\'autre cheville croisée derrière.',
      'Se tenir légèrement à un mur pour l\'équilibre.',
      'Montée explosive, descente très lente (4s) sous le niveau neutre.',
      'Sentir un bon étirement du mollet en bas.',
    ],
    sets: '3',
    reps: '12–15/jambe',
    rest: '60s',
  },
  // ── Corps entier ──────────────────────────────────────────────────────────
  {
    id: 'burpee',
    name: 'Burpee',
    description: 'Exercice polyarticulaire cardio-force qui sollicite l\'ensemble du corps.',
    difficulty: 'Intermédiaire',
    muscles: ['Corps entier'],
    instructions: [
      'Debout, descendre en squat, poser les mains au sol.',
      'Sauter les pieds en arrière pour se retrouver en position de pompe.',
      'Faire une pompe (option) puis ramener les pieds.',
      'Sauter verticalement, bras en l\'air — atterrir en souplesse.',
    ],
    sets: '3',
    reps: '8–15',
    rest: '90s',
  },
  {
    id: 'turkish-getup',
    name: 'Turkish Get-up',
    description: 'Mouvement complexe au sol qui développe la stabilité totale du corps.',
    difficulty: 'Avancé',
    muscles: ['Corps entier', 'Épaules', 'Abdominaux'],
    instructions: [
      'Allongé, bras droit tendu vers le plafond (avec ou sans poids).',
      'S\'asseoir sur le coude, puis la main gauche au sol.',
      'Lever la hanche, passer en position de fente basse.',
      'Se lever complètement — inverser le mouvement pour redescendre.',
    ],
    sets: '3',
    reps: '3–5/côté',
    rest: '90s',
  },
  {
    id: 'thruster',
    name: 'Thruster (poids du corps)',
    description: 'Combinaison squat + développé — explosion explosive corps entier.',
    difficulty: 'Intermédiaire',
    muscles: ['Corps entier', 'Quadriceps', 'Épaules'],
    instructions: [
      'Pieds largeur d\'épaules, mains sur les épaules (ou avec bouteilles d\'eau).',
      'Descendre en squat complet.',
      'Remonter de façon explosive et enchaîner avec un développé au-dessus.',
      'Le mouvement doit être fluide et continu, une seule action.',
    ],
    sets: '3',
    reps: '10–12',
    rest: '75s',
  },
  {
    id: 'inchworm',
    name: 'Inchworm',
    description: 'Mobilité dynamique et renforcement du gainage — idéal en échauffement ou finisher.',
    difficulty: 'Débutant',
    muscles: ['Corps entier', 'Dos', 'Abdominaux'],
    instructions: [
      'Debout, se pencher pour poser les mains au sol devant les pieds.',
      'Marcher avec les mains jusqu\'à la position de pompe, jambes tendues.',
      'Optionnel : faire une pompe.',
      'Marcher avec les pieds vers les mains — revenir debout.',
    ],
    sets: '3',
    reps: '8–10',
    rest: '45s',
  },
];
